version: '3.9'

services:

  php-env:
    build: ./.docker
    volumes:
      - .:/usr/src/myapp
    ports:
      - 8000:80

  mysql_db:
      image: mysql:latest
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      ports:
      - 8888:3306
      environment:
        MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8001:80
    environment:
      - PMA_ARBITRARY=1
